@echo off
cd /d "%~dp0"

echo -- Sounds.lua (auto-generated by GenerateSounds.bat)> Sounds.lua
echo -- Do not edit manually. Run GenerateSounds.bat after adding new sound files.>> Sounds.lua
echo local KPI = KPI_Global>> Sounds.lua
echo.>> Sounds.lua
echo KPI.soundFiles = {>> Sounds.lua

for %%f in (sounds\*.mp3 sounds\*.ogg sounds\*.wav) do (
    echo     "%%~nxf",>> Sounds.lua
)

echo }>> Sounds.lua

echo Done! Sounds.lua updated. Reload your UI in-game.
pause
