#!/bin/bash
cd "$(dirname "$0")"

echo "-- Sounds.lua (auto-generated by GenerateSounds.sh)" > Sounds.lua
echo "-- Do not edit manually. Run GenerateSounds.sh after adding new sound files." >> Sounds.lua
echo "local KPI = KPI_Global" >> Sounds.lua
echo "" >> Sounds.lua
echo "KPI.soundFiles = {" >> Sounds.lua

for f in sounds/*.mp3 sounds/*.ogg sounds/*.wav; do
    [ -f "$f" ] && echo "    \"$(basename "$f")\"," >> Sounds.lua
done

echo "}" >> Sounds.lua

echo "Done! Sounds.lua updated. Reload your UI in-game."
